/* Client & Market Opportunities data — grounded in
   ideyaLabs_Transportation_AI_Client_Fit_Target_Accounts.docx.
   Fidelity flags preserved from the source: FACT, ASSESSMENT/INFERENCE, NEEDS VALIDATION.
   No company metric, score, ranking, or buyer is invented here. */

window.MARKET = {
  meta: {
    title: "Transportation AI — Client Fit & Target Account Strategy",
    subtitle: "Converting the prioritized Transportation AI portfolio into a client acquisition and expansion plan.",
    prioritizedSolutions: 10,
    existingClients: 3,
    tierAProspects: 7,
    totalProspects: 35,
    topExistingOpportunity: "Bison Transport / Daylight Transport (tie) — Invoice Audit & Payment Agent",
    topAgentOpportunity: "Invoice Audit & Payment Agent (fastest to revenue)",
    topNewLogo: "DSV (post-DB Schenker) — Bridge, Score 8.05 (highest-scored prospect)",
    recommendedFirstPilot: "Daylight Transport — EDI-210 invoice-audit pilot via Boomi (cleanest data)",
    recommendedFlagship: "Vehicle Damage & Claims Mgmt Agent (Hödlmayr, adapted) — strongest differentiation"
  },

  fitLevels: {
    A: { label: "HIGH FIT", cls: "fit-a" },
    B: { label: "STRONG POTENTIAL", cls: "fit-b" },
    C: { label: "VALIDATE", cls: "fit-c" },
    D: { label: "LOW FIT", cls: "fit-d" },
    E: { label: "NOT A FIT", cls: "fit-e" }
  },

  tiers: {
    A: { label: "TIER A — PRIORITY TARGET", cls: "tier-a" },
    B: { label: "TIER B — HIGH POTENTIAL", cls: "tier-b" },
    C: { label: "TIER C — NURTURE", cls: "tier-c" },
    D: { label: "TIER D — LOW PRIORITY", cls: "tier-d" }
  },

  /* The 10 prioritized solutions (Top 7 + 3 pulled-back), retaining roadmap tier & score.
     detailId links to the existing product detail page where one exists. */
  solutions: [
    { key:"invoice-audit", name:"Invoice Audit, Discrepancy Resolution & Payment Agent", tier:"TIER 1 — Build Now", score:"8.40", detailId:"invoice-audit", def:"Audits freight invoices, drafts/negotiates disputes, releases payment autonomously." },
    { key:"exception-mgmt", name:"Shipment Exception Management & Disruption Response Agent", tier:"TIER 1 — Build Now", score:"8.20", detailId:"exception-mgmt", def:"Observes shipment status, reasons about disruptions, acts to resolve them." },
    { key:"claims", name:"Freight Claims Management & Recovery Agent", tier:"TIER 1 — Build Now", score:"7.80", detailId:"claims", def:"Detects claim-eligible exceptions, files and chases claims autonomously." },
    { key:"carrier-fraud", name:"Carrier Identity, Onboarding & Fraud-Prevention Agent", tier:"TIER 2 — Build Next", score:"7.60", detailId:"carrier-fraud", def:"Verifies and continuously monitors carriers for fraud/identity risk." },
    { key:"procurement", name:"Dynamic Freight Procurement & Carrier-Sourcing Agent", tier:"TIER 2 — Build Next", score:"7.15", detailId:"procurement", def:"Works the routing guide and re-tenders freight against market rates autonomously." },
    { key:"detention", name:"Detention & Dock Appointment Coordination Agent", tier:"TIER 2 — Build Next", score:"6.90", detailId:"detention", def:"Schedules/renegotiates dock appointments and pursues detention invoices." },
    { key:"freightlink", name:"FreightLink — Unified Visibility Hub", tier:"TIER 2 — Build Next (platform)", score:"6.70", detailId:"freightlink", def:"Normalizes fragmented carrier tracking into one visibility feed." },
    { key:"quoting", name:"Freight Quoting & RFQ Response Agent", tier:"TIER 3 — Defer", score:"6.45", detailId:"quoting", def:"Reads inbound RFQs and responds autonomously within minutes." },
    { key:"empty-mile", name:"Empty-Mile / Dynamic Backhaul Agent", tier:"TIER 3 — Defer", score:"6.45", detailId:"empty-mile", def:"Sources and books backhaul loads to cut empty-mile percentage." },
    { key:"bridge", name:"Bridge — TMS Integration Gateway", tier:"TIER 2* — Build Next (platform)", score:"6.00", detailId:"bridge", def:"Bridges legacy EDI/flat-file TMS platforms to modern APIs." }
  ],

  /* Fit matrix: solutionKey -> { bison, daylight, hodlmayr } fit level + rationale (for tooltips) */
  fitMatrix: [
    { key:"invoice-audit", bison:["A","Multi-division invoice audit already outsourced to Navix (2026)"], daylight:["A","≈2,500 invoices/day through an EDI-integrated TMS"], hodlmayr:["C","Two-sided billing (OEM + subcontractors); no documented accuracy problem — adapted"] },
    { key:"exception-mgmt", bison:["B","Multi-division, cross-border, intermodal network; 'Advanced Warning' already exists"], daylight:["B","Time-critical 2–3 day model makes exceptions proportionally costly; EDI 214 flows"], hodlmayr:["B","Complex rail-truck handoff network — adapted to vehicle movement"] },
    { key:"claims", bison:["B","Meaningful claims volume despite <0.1% loss ratio"], daylight:["B","MyDaylight claims-intake portal already exists"], hodlmayr:["B","Existing 360° vehicle-photography workflow — strongest evidence, adapted"] },
    { key:"carrier-fraud", bison:["A","Tens-of-thousands-truck brokerage carrier network"], daylight:["E","Asset-based LTL carrier — not a broker managing a third-party panel"], hodlmayr:["D","Not a freight broker business model"] },
    { key:"procurement", bison:["C","Brokerage arm is the only plausible angle"], daylight:["E","Sells capacity on its own network; not procuring capacity"], hodlmayr:["E","Not a capacity-procuring business model"] },
    { key:"detention", bison:["C","LCV/dedicated freight plausibly involves appointments — inference only"], daylight:["C","National LTL terminal network plausibly has appointment complexity — inference"], hodlmayr:["D","Already runs Syncrotess AI yard/workshop scheduling (solved)"] },
    { key:"freightlink", bison:["C","Only Bison lacks an already-built equivalent visibility tool"], daylight:["D","MyDaylight portal + EDI 214 feed already provide visibility (solved)"], hodlmayr:["D","LCS real-time vehicle tracking already exists (solved)"] },
    { key:"quoting", bison:["C","Possible; needs validation"], daylight:["B","Live public Rate Quote API — real appetite/infrastructure to extend"], hodlmayr:["E","Not an RFQ-driven business model"] },
    { key:"empty-mile", bison:["C","Asset fleet could benefit; needs validation"], daylight:["E","LTL consolidation already solves trailer utilization structurally"], hodlmayr:["B","Specialized car-carrier/rail-wagon fleet — most plausible empty-leg case, adapted"] },
    { key:"bridge", bison:["C","2025 MasterMind TMS consolidation still maturing"], daylight:["D","Already solved this itself (Boomi/Sterling Gentran integration)"], hodlmayr:["C","Gartner KG acquisition closing summer 2026 — M&A trigger, adapted"] }
  ],

  clients: [
    {
      id:"bison",
      name:"Bison Transport",
      location:"Winnipeg, Manitoba, Canada",
      type:"Asset-based carrier + non-asset brokerage",
      fit:"A",
      fitNote:"High Fit — warm account with active OIA proposal",
      bestOpportunity:"Invoice Audit & Payment Agent — expands the existing Order Intelligence Agent relationship",
      recommendedPilot:"Invoice-audit pilot on one division's invoices (brokerage or asset), benchmarked against the current Navix process",
      buyer:"VP Finance / freight-payment leadership (economic buyer: CFO)",
      keyProblem:"Multi-division (asset + brokerage) invoice audit — Navix selected April 2026 to standardize invoice review across both divisions",
      kpiRoi:"% of audited freight spend recovered; days from invoice receipt to resolved payment. Self-funding.",
      validation:"Current scope and contract status of the Navix engagement; Bison's invoice volume for sizing.",
      model:"≈3,000 tractors, 10,000 trailers/containers; asset-based truckload (dry van, reefer, flat deck), dedicated, intermodal, LTL, expedited; plus a non-asset brokerage division with a partner-carrier network in the tens of thousands of trucks. Operates across all 48 contiguous US states, Canada, and Mexico. Privately held by James Richardson & Sons since 2021.",
      facts:[
        ["FACT","Selected Mastery Logistics' MasterMind TMS (2025) to unify Canada/US/Mexico, asset and non-asset systems."],
        ["FACT","Selected Navix, an AI-powered freight-audit platform (April 2026), to standardize invoice review across both divisions."],
        ["PROJECT-MATERIAL FACT","ideyaLabs previously scoped an 'Order Intelligence Agent (OIA)' technical proposal for Bison — email order ingestion, AI parsing, TMS order-entry automation, Day-20 PoC gate. The single strongest existing-client signal in the analysis."],
        ["FACT","Won the TCA Fleet Safety Award grand prize three consecutive years (2023–2025); claims/loss ratio under 0.1%."]
      ],
      opportunities:[
        { rank:1, solution:"Invoice Audit, Discrepancy Resolution & Payment Agent", detailId:"invoice-audit", fidelity:"FACT",
          why:"Navix selection (April 2026) is direct evidence of the billing-complexity pain and budget/appetite. Angle: differentiation (full negotiate-and-pay agent, not just audit-and-flag) or a complementary play alongside Navix — not a greenfield pitch.",
          problem:"Bison selected Navix specifically to standardize invoice review/approval across its asset and brokerage divisions, replacing manual/fragmented processes.",
          buyer:"VP Finance / freight-payment leadership; economic buyer CFO.",
          kpi:"% of audited freight spend recovered; days from invoice receipt to resolved payment.",
          pilot:"One division (e.g., brokerage) or one lane group; ingest 60–90 days of historical invoices; benchmark ideyaLabs' recovery rate against the current Navix/manual baseline." },
        { rank:2, solution:"Carrier Identity, Onboarding & Fraud-Prevention Agent", detailId:"carrier-fraud", fidelity:"VALIDATE",
          why:"Scale of the tens-of-thousands-truck brokerage carrier network is the clearest structural signal; tri-national US–Canada–Mexico operations add cross-border verification complexity.",
          problem:"A partner-carrier network this size is structurally exposed to double-brokering and identity-fraud patterns, but no public Bison-specific fraud incident was found.",
          buyer:"Head of Carrier Procurement / VP Brokerage.",
          kpi:"Onboarding cycle time; fraud/loss incidents avoided per $ of brokered freight.",
          pilot:"Onboarding-verification MVP against 1–2 vetting APIs for new brokerage carriers over a defined period." },
        { rank:3, solution:"Shipment Exception Management & Disruption Response Agent", detailId:"exception-mgmt", fidelity:"VALIDATE",
          why:"Multi-division, cross-border, intermodal network creates real exception surface area; ≈85% of truckload freight already GPS-tracked. Bison already markets an 'Advanced Warning' disruption-detection capability.",
          problem:"Exception management is a stated priority; whether it acts autonomously or only alerts is not publicly documented.",
          buyer:"VP Operations.",
          kpi:"OTIF improvement; exception resolution time.",
          pilot:"Single-mode/region pilot layered on top of existing GPS/Advanced Warning data." },
        { rank:4, solution:"Freight Claims Management & Recovery Agent", detailId:"claims", fidelity:"VALIDATE",
          why:"Even a low claims RATE generates meaningful claims VOLUME across ≈3,000 owned tractors plus the brokerage network.",
          problem:"Claims/loss ratio under 0.1% suggests a well-run operation; opportunity is whether filing is as complete as it could be at this scale.",
          buyer:"Claims Manager.",
          kpi:"Claims filing rate; recovery rate.",
          pilot:"LTL/brokerage-focused claims-detection pilot over a defined shipment set." },
        { rank:5, solution:"Detention & Dock Appointment Coordination Agent", detailId:"detention", fidelity:"NEEDS VALIDATION",
          why:"Included because the brief explicitly asks about detention/dock for Bison. LCV operations (13% of miles) and dedicated contracts plausibly involve appointments — inference, not evidence.",
          problem:"Not evidenced publicly whether Bison experiences meaningful detention/dock friction.",
          buyer:"Head of Dispatch / VP Operations.",
          kpi:"Detention hours per stop; detention-invoice collection rate.",
          pilot:"Single facility pair or lane, used first to establish a baseline detention frequency before proposing automation." }
      ],
      firstEngagement:{
        solution:"Invoice Audit & Payment Agent",
        pilot:"One division's invoices, 60–90 days of history, benchmarked against the current Navix/manual baseline.",
        success:"A measurably higher (or genuinely complementary) recovery rate than the current process, validated on real Bison data — enough to justify expanding beyond the pilot division.",
        expansion:"Order Intelligence Agent (in production) → Invoice Audit & Payment Agent (pilot, shared document-intelligence infrastructure) → Carrier Fraud & Onboarding Agent → Freight Claims Management Agent → platform relationship spanning both asset and brokerage divisions."
      }
    },
    {
      id:"daylight",
      name:"Daylight Transport",
      location:"Cypress, California, USA",
      type:"Privately held, founder-led expedited LTL carrier",
      fit:"A",
      fitNote:"High Fit — cleanest data, no incumbent conflict",
      bestOpportunity:"Invoice Audit & Payment Agent — the most precisely quantified opportunity in this document",
      recommendedPilot:"EDI-210-based invoice-audit pilot connected via Daylight's own preferred integration pattern, Boomi",
      buyer:"CIO (led the Boomi/TruckMate integration) or VP Finance",
      keyProblem:"≈2,500 invoices/day flow through an EDI-210-integrated TruckMate TMS, handled by a 9-person finance team",
      kpiRoi:"% of audited spend recovered; days to resolved payment; reduced manual reconciliation load. Self-funding.",
      validation:"Daylight's current invoice error/dispute rate; who owns invoice audit today (internal vs vendor).",
      model:"Expedited LTL using a two-driver sleeper-team model to cut coast-to-coast transit from a standard 7–15 days to 2–3 days, with offshore transload to Hawaii, Alaska, and Puerto Rico. Per Transport Topics 2026: 323 tractors, 607 trailers (#75 nationally). Unusually mature tech stack for its size.",
      facts:[
        ["FACT","Trimble TruckMate TMS (since 2012) integrated via Dell Boomi with IBM Sterling Gentran for EDI; public APIs for rate quoting/pickup/tracing; mid-transition to Oracle Fusion ERP; BlackLine for automated reconciliation."],
        ["FACT","BlackLine case study: Daylight processes ≈2,500 invoices/day through a 9-person finance team, with EDI 210 (freight invoice) and 214 (shipment status) already integrated."],
        ["FACT","BlackLine cut close-cycle time from 6 to 3 days — this team responds well to automation."],
        ["NOTE","No project-material evidence (proposals, prior engagements) found for Daylight — assessments rely on external research plus solution-to-operating-model reasoning. Most evidence-rich of the three for sizing an Invoice Audit pilot."]
      ],
      opportunities:[
        { rank:1, solution:"Invoice Audit, Discrepancy Resolution & Payment Agent", detailId:"invoice-audit", fidelity:"FACT",
          why:"The single most directly evidenced Invoice Audit fit of the three existing clients — real invoice-volume data, not inference.",
          problem:"≈2,500 invoices/day flow through TruckMate via an EDI 210 integration built on Boomi/Sterling Gentran, handled by a 9-person finance team.",
          buyer:"CIO (led the Boomi/TruckMate integration) or VP Finance.",
          kpi:"% of audited spend recovered; days to resolved payment; reduction in the finance team's manual reconciliation load.",
          pilot:"Connect to the existing EDI 210 feed via Boomi — Daylight's stated preferred integration pattern; audit 60–90 days of historical invoices against TruckMate rating data." },
        { rank:2, solution:"Freight Claims Management & Recovery Agent", detailId:"claims", fidelity:"FACT",
          why:"The intake layer already exists (MyDaylight online claims submission); the agent would sit behind it rather than requiring a new customer-facing surface.",
          problem:"Online claims submission exists via MyDaylight, but nothing public shows proactive claim detection or automated filing.",
          buyer:"Customer Service / Claims leadership.",
          kpi:"Claims filing rate; recovery rate.",
          pilot:"Proactive claim-detection pilot layered on MyDaylight's existing intake data for a defined lane set." },
        { rank:3, solution:"Shipment Exception Management & Disruption Response Agent", detailId:"exception-mgmt", fidelity:"VALIDATE",
          why:"An expedited/time-critical carrier has the most to lose from unmanaged exceptions, and already has the EDI 214 status feed an exception agent needs.",
          problem:"Speed (2–3 day coast-to-coast) makes exceptions proportionally more costly than for a standard LTL carrier; EDI 214 already integrated.",
          buyer:"VP Operations.",
          kpi:"On-time percentage against the 2–3 day guaranteed service; exception resolution time.",
          pilot:"One lane, or one offshore leg (e.g., the Hawaii transload via Long Beach), given the added complexity of transload exceptions." },
        { rank:4, solution:"Freight Quoting & RFQ Response Agent", detailId:"quoting", fidelity:"FACT",
          why:"The existing public Rate Quote API is evidence of appetite and infrastructure — the opportunity is extending it (complex/negotiated scenarios, inbound freight-forwarder RFQs), not rebuilding it.",
          problem:"Daylight already exposes a public Rate Quote API via its Apigee portal — quoting is a live, technology-forward function.",
          buyer:"VP Sales / Pricing.",
          kpi:"Quote-to-win conversion rate; turnaround time for non-standard requests.",
          pilot:"A narrowly scoped extension — e.g., automated response for one category of non-standard RFQ — rather than a rebuild of an already-live API." },
        { rank:5, solution:"Detention & Dock Appointment Coordination Agent", detailId:"detention", fidelity:"NEEDS VALIDATION",
          why:"Included because the brief explicitly asks about dock/detention for Daylight. A national LTL terminal network with team-driver linehaul plausibly has appointment complexity — inference, not evidence.",
          problem:"Not evidenced publicly whether Daylight's terminal/P&D network experiences meaningful detention or dock-scheduling friction.",
          buyer:"VP Operations / Terminal Operations.",
          kpi:"Detention hours per stop; on-time terminal turnaround.",
          pilot:"A discovery conversation at 1–2 terminals before committing to a build." }
      ],
      firstEngagement:{
        solution:"Invoice Audit & Payment Agent",
        pilot:"60–90 day pilot connected via Boomi (Daylight's own preferred integration pattern), against its EDI 210 feed and TruckMate rating data.",
        success:"Quantifiable before/after invoice-audit numbers on real Daylight data — the flagship case study candidate (clean data, single-vendor narrative).",
        expansion:"Invoice Audit & Payment Agent (pilot via Boomi) → Production → Freight Claims Management Agent → Shipment Exception Management Agent (EDI 214 already flows) → platform relationship."
      }
    },
    {
      id:"hodlmayr",
      name:"Hödlmayr International",
      location:"Schwertberg, Austria",
      type:"Finished-vehicle (automotive) logistics — NOT a freight carrier",
      fit:"B",
      fitNote:"Strong Potential — needs adaptation + client validation",
      bestOpportunity:"Vehicle Damage & Claims Management Agent (adapted) — built on the existing 360° vehicle-photography workflow",
      recommendedPilot:"Single-VLC, single-damage-category pilot built on the existing 360° vehicle-photography workflow — after a validation conversation",
      buyer:"VLC Operations / Quality leadership",
      keyProblem:"Vehicle-condition documentation (360° photography) exists, but claims filing is not shown to be automated",
      kpiRoi:"Claims filed as % of damage incidents detected; claim cycle time. Medium–High.",
      validation:"Whether damage-claims filing against carriers/insurers/OEMs from the existing photography is manual today.",
      model:"Family-owned, third-generation finished-vehicle logistics provider — door-to-door: releasing-agent services, road and rail vehicle transport, vehicle logistics centers (VLCs) for storage/technical prep, and dealer/end-customer delivery. This is a fundamentally different business from freight — none of the seven solutions applies unmodified.",
      autoNote:"IMPORTANT: Hödlmayr is an automotive/vehicle-logistics company, not a generic LTL/FTL carrier. All opportunities below are adapted from the freight portfolio; two solutions (FreightLink, Detention & Dock) are LOW FIT specifically because Hödlmayr already runs the equivalent capability itself (LCS and Syncrotess). Zero HIGH FIT is the correct outcome of not force-fitting.",
      facts:[
        ["FACT (2023)","≈€400M+ revenue, ≈1,700 employees, ≈1.9M vehicles handled/year, 16–19 sites across Central/Eastern/Southern Europe, ≈1.3M m² storage for ≈55,000 vehicles, 600 vehicle-transport trucks / 580 subcontracted carriers, 24 full train sets (targeting 29), ≈500 rail wagons (targeting ≈1,000)."],
        ["FACT","Already runs INFORM's Syncrotess AI-based yard/workshop scheduling (2022+), an in-house TIS with EDI/REST APIs, an LCS real-time vehicle-tracking portal, and holds TISAX Level 2 certification."],
        ["FACT","Automotive-engineering service line already performs 360° vehicle photography as part of its VLC process."],
        ["FACT","Announced acquisition of Gartner KG's commercial high & heavy vehicle division (May 2026), into a new 'Hödlmayr High & Heavy GmbH' entity; closing expected summer 2026 — a live systems-integration trigger."]
      ],
      opportunities:[
        { rank:1, solution:"Vehicle Damage & Claims Management Agent (adapted)", base:"Freight Claims Management & Recovery Agent", detailId:"claims", fidelity:"FACT",
          adaptation:"Replace freight POD/BOL claims logic with vehicle-condition documentation and OEM/insurer claims workflows. The pattern — detect an exception from existing documentation, then file a claim automatically — transfers directly; only the exception source changes.",
          why:"The hardest part of a damage-claims agent — reliable before/after visual evidence — already exists (360° photography). The strongest-evidenced opportunity of the five.",
          problem:"360° vehicle photography already exists in the VLC process; NEEDS VALIDATION whether damage-claims filing from that photography is manual today.",
          buyer:"VLC Operations / Quality leadership.",
          kpi:"Claims filed as % of damage incidents detected; claim cycle time.",
          pilot:"One VLC site, one damage category (e.g., transport-related exterior damage), using the existing 360° photography as the data source." },
        { rank:2, solution:"Vehicle Movement Exception Management Agent (adapted)", base:"Shipment Exception Management & Disruption Response Agent", detailId:"exception-mgmt", fidelity:"FACT",
          adaptation:"Exception triggers become rail block-train delays, truck breakdowns, and port/customs holds on vehicle shipments. Resolution actions become rebooking rail slots or reassigning subcontracted truck carriers.",
          why:"Scale of rail-truck coordination is the clearest operational-complexity signal found for Hödlmayr. Would become the shared infrastructure a Backhaul agent reuses.",
          problem:"Coordinates 24+ train sets, 500+ rail wagons, 600 trucks across 16–19 sites — a complex multimodal handoff network. NEEDS VALIDATION whether disruptions are managed reactively today.",
          buyer:"Transport Logistics / Rail Operations leadership.",
          kpi:"On-time dealer-delivery rate; rail-to-truck handoff delay frequency.",
          pilot:"One high-volume rail corridor — e.g., the Barcelona–Schwertberg block train (≈35,000 vehicles/year)." },
        { rank:3, solution:"Car-Carrier & Rail-Wagon Backhaul / Capacity Optimization Agent (adapted)", base:"Empty-Mile / Dynamic Backhaul Agent", detailId:"empty-mile", fidelity:"VALIDATE",
          adaptation:"Backhaul matching for specialized car-carrier trucks and rail wagons, not general freight. Car-carrier equipment cannot flex into general freight, so the problem is narrower (vehicle-to-vehicle) but potentially higher-value.",
          why:"A genuinely novel, high-specialization opportunity where a generic freight empty-mile tool would not apply.",
          problem:"A 600-truck, 500+-wagon specialized fleet moving 1.9M vehicles/year almost certainly has return-leg utilization gaps.",
          buyer:"Fleet / Transport Operations leadership.",
          kpi:"Empty-leg percentage for car-carrier trucks and rail wagons.",
          pilot:"One regional truck fleet or one rail corridor, first measuring the current empty-leg percentage." },
        { rank:4, solution:"Vehicle Logistics Billing & Subcontractor Payment Audit Agent (adapted)", base:"Invoice Audit, Discrepancy Resolution & Payment Agent", detailId:"invoice-audit", fidelity:"NEEDS VALIDATION",
          adaptation:"Replace one-sided freight-invoice auditing with a two-sided billing problem: (a) Hödlmayr's billing to OEM customers for storage/prep/transport, and (b) payments to its 580 subcontracted vehicle-transport carriers.",
          why:"Every logistics business with this many billable service lines plausibly has some invoice-accuracy leakage, but Hödlmayr's own disclosures don't confirm it.",
          problem:"Not evidenced publicly whether either billing direction has a documented accuracy or dispute problem.",
          buyer:"Finance / Controlling leadership.",
          kpi:"Billing-dispute rate; days to resolve billing discrepancies.",
          pilot:"A discovery conversation with Finance before any build commitment." },
        { rank:5, solution:"Systems-Integration Support for the Gartner KG Acquisition (adapted)", base:"Bridge — TMS Integration Gateway", detailId:"bridge", fidelity:"FACT",
          adaptation:"Bridge's 'legacy TMS to modern API' pattern applies directly if Gartner KG's high & heavy division runs different systems than Hödlmayr's in-house TIS/LCS stack — likely true immediately after an acquisition.",
          why:"The most time-boxed, evidence-backed trigger of any Hödlmayr opportunity — the acquisition is recent and integration work is imminent.",
          problem:"Gartner KG acquisition (May 2026) integrating into 'Hödlmayr High & Heavy GmbH', closing summer 2026 — a live, near-term systems-integration need.",
          buyer:"IT / Group Integration leadership.",
          kpi:"Time to bring Gartner KG's transport data into Hödlmayr's TIS/LCS environment.",
          pilot:"A scoping conversation timed to the acquisition's summer 2026 closing." }
      ],
      firstEngagement:{
        solution:"Vehicle Damage & Claims Management Agent (adapted)",
        pilot:"No pilot yet — a scoping/validation conversation with VLC Operations/Quality leadership first, using the 360° vehicle-photography workflow as the reference. Single-site, single-damage-category pilot only once the process gap is confirmed.",
        success:"A genuinely differentiated, novel agentic use case (vehicle-damage detection + claims filing) that no freight-focused competitor can point to — the best AI-agent showcase.",
        expansion:"Vehicle Damage & Claims Management Agent (pilot, one VLC site) → Production → Vehicle Movement Exception Management Agent → Car-Carrier & Rail-Wagon Backhaul Agent → platform relationship spanning a new automotive-logistics product line."
      }
    }
  ]
  ,

  /* Target accounts. region: na | eu | auto. tier from source scoring. adapted=true for automotive. */
  prospects: [
    { name:"Estes Express Lines", region:"na", hq:"Richmond, VA", tier:"A", score:"7.75", industry:"LTL", geo:"United States",
      note:"",
      model:"Employee-owned national LTL carrier; ≈$5.8B revenue, 24,000+ employees, 300+ terminals, ≈10,600 tractors, 42,000+ trailers; 5 new terminals + 16 relocated/expanded + 1,038 doors added in 2025 (≈7% of the network touched in one year).",
      solution:"Invoice Audit / Exception Mgmt / Bridge",
      why:"Large national LTL carrier whose scale and active network expansion support a strong Invoice Audit / Exception Mgmt / Bridge fit. No confirmed AI initiative found, but scale alone supports the fit.",
      pain:"300+ terminal LTL network with 7% of footprint under active construction (2025)",
      buyer:"VP Finance / VP Operations", strategic:"High-scale LTL invoice volume and multi-terminal complexity make it a strong Tier A target.",
      action:"Outbound — lead with the invoice-audit / exception-management fit" },
    { name:"Schneider National", region:"na", hq:"Green Bay, WI", tier:"A", score:"7.50", industry:"FTL", geo:"United States",
      model:"Publicly traded truckload/intermodal/logistics carrier; TTM revenue ≈$5.59B; ≈12,291 average trucks, 52,323 trailers (Q3 2025).",
      solution:"Detention & Dock Coordination Agent",
      why:"Partnered with EXL (AI/data company) to digitize appointment scheduling — 50% cycle-time improvement, 24% cost-per-appointment reduction — direct, sourced proof Schneider funds third-party AI for exactly this problem.",
      pain:"Proven appetite: EXL AI partnership cut appointment cycle time 50%",
      buyer:"VP Operations / COO", strategic:"Reference the EXL result directly.",
      action:"Outbound — reference the EXL result directly" },
    { name:"TForce Freight (TFI International)", region:"na", hq:"Richmond, VA / Montreal, QC parent", tier:"A", score:"7.75", industry:"LTL", geo:"United States / Canada",
      model:"LTL division of TFI International, built almost entirely by acquisition — 19 separate LTL 'Operating Companies'; TFI generated >US$8B total revenue in 2024.",
      solution:"Bridge (TMS Integration Gateway)",
      why:"19 distinct LTL operating companies almost certainly means fragmented, acquired legacy TMS platforms — a textbook Bridge use case; large cross-border US/Canada network also supports Carrier Fraud fit.",
      pain:"19 separate LTL operating companies, almost certainly on fragmented legacy TMS platforms",
      buyer:"CIO / VP IT", strategic:"Systems-consolidation angle.",
      action:"Outbound — lead with systems-consolidation angle" },
    { name:"J.B. Hunt Transport Services", region:"na", hq:"Lowell, AR", tier:"A", score:"7.55", industry:"FTL / Brokerage", geo:"United States",
      model:"Publicly traded diversified carrier — Intermodal, Dedicated, Final Mile, and Integrated Capacity Solutions (ICS) brokerage, unified under J.B. Hunt 360; FY2025 revenue $12.0B; ICS segment revenue $1.109B (down 9% YoY).",
      solution:"Shipment Exception Mgmt Agent",
      why:"Declining brokerage volume (-7% YoY) alongside a new strategic alliance with Google Cloud to accelerate next-generation supply-chain technology — a large, technology-forward carrier actively looking for an edge.",
      pain:"ICS brokerage volume down 7% YoY alongside a new Google Cloud AI alliance",
      buyer:"VP Operations / control-tower lead", strategic:"Align with the Google Cloud initiative.",
      action:"Outbound — align with the Google Cloud initiative" },
    { name:"Forward Air (incl. Omni Logistics)", region:"na", hq:"Greeneville, TN", tier:"B", score:"7.40", industry:"LTL", geo:"United States",
      model:"Publicly traded expedited LTL/ground network; merged with Omni Logistics (2024) amid litigation and a ≈$1B net-loss quarter from goodwill impairment; Q2 2025 revenue $618.8M (down 3.9% YoY).",
      solution:"Invoice Audit & Claims Mgmt Agent",
      why:"Active, disclosed post-merger disruption — two companies' invoice and claims systems colliding is precisely the scenario these two agents are built for.",
      pain:"Active post-merger invoice/systems disruption", buyer:"CFO / VP Finance", strategic:"Post-merger systems collision.",
      action:"Outbound — post-merger systems angle" },
    { name:"ArcBest / ABF Freight", region:"na", hq:"Fort Smith, AR", tier:"B", score:"7.40", industry:"LTL", geo:"United States",
      model:"Publicly traded holding company; ABF Freight is its unionized national LTL subsidiary alongside asset-light truckload/expedite units.",
      solution:"Freight Quoting / Dynamic Procurement Agent",
      why:"Deployed an AI-based city-route optimization tool generating over $1M/month in operating-income improvement, plus a generative-AI customer-service pilot — proven internal appetite and budget for operational AI.",
      pain:"Proven internal AI ROI ($1M/month from city-route optimization)", buyer:"VP Sales / Pricing", strategic:"Strongest disclosed internal-AI trigger of any prospect.",
      action:"Outbound — reference proven internal AI ROI" },
    { name:"Knight-Swift Transportation", region:"na", hq:"Phoenix, AZ", tier:"B", score:"7.35", industry:"FTL / LTL", geo:"United States",
      model:"Largest publicly traded truckload carrier in North America — Truckload, LTL, and Intermodal segments; FY2025 revenue $7.47B; ≈26,187 average combined tractors.",
      solution:"Invoice Audit & Carrier Fraud Agent",
      why:"Multi-segment scale (TL + LTL + intermodal + owner-operators, incl. folded-in U.S. Xpress) creates high invoice-audit and carrier-onboarding complexity; already runs Netradyne AI for safety.",
      pain:"Multi-segment invoice complexity incl. folded-in U.S. Xpress", buyer:"CFO / VP Brokerage", strategic:"Multi-segment complexity.",
      action:"Outbound — multi-segment complexity angle" },
    { name:"Old Dominion Freight Line", region:"na", hq:"Thomasville, NC", tier:"B", score:"7.30", industry:"LTL", geo:"United States",
      model:"Publicly traded, non-union national LTL carrier; 261 service centers; committing $575M in 2025 network capex, including $50M for IT/customer API integration and visibility tech.",
      solution:"Invoice Audit / FreightLink",
      why:"High-density interline/accessorial billing volume; the $50M technology capex line is a direct, dated modernization signal.",
      pain:"High-density interline/accessorial billing; $50M IT/visibility capex line", buyer:"CFO / VP IT", strategic:"Dated modernization capex signal.",
      action:"Outbound — reference the $50M IT capex" },
    { name:"Saia, Inc.", region:"na", hq:"Johns Creek, GA", tier:"B", score:"7.20", industry:"LTL", geo:"United States",
      model:"Publicly traded national LTL carrier mid-way through an aggressive terminal-expansion strategy; 214 terminals at YE2024, targeting 230; >$2B invested in network expansion over 3 years.",
      solution:"Detention & Dock / Exception Mgmt Agent",
      why:"Newly opened terminals run operating ratios in the mid-to-upper 90s vs. mature terminals in the upper 70s — the greenfield terminals are exactly where these two agents move the P&L fastest.",
      pain:"Greenfield terminals running poor operating ratios", buyer:"VP Operations / COO", strategic:"Greenfield-terminal P&L leverage.",
      action:"Outbound — greenfield-terminal angle" },
    { name:"Werner Enterprises", region:"na", hq:"Omaha, NE", tier:"B", score:"6.90", industry:"FTL", geo:"United States",
      model:"Publicly traded truckload carrier (One-Way, Dedicated) with a logistics/brokerage arm; FY2025 revenue $2.97B (down 2%); tractor fleet reduced to 7,100 units.",
      solution:"Invoice Audit & Payment Agent",
      why:"Publicly guided to a $45M cost-savings target with an explicit strategic realignment toward efficiency — a carrier under active cost pressure is a strong buyer for a self-funding audit agent.",
      pain:"Publicly guided $45M cost-savings target", buyer:"CFO", strategic:"Cost pressure + self-funding fit.",
      action:"Outbound — self-funding cost-reduction angle" },
    { name:"C.H. Robinson", region:"na", hq:"Eden Prairie, MN", tier:"B", score:"6.90", industry:"3PL / Brokerage", geo:"Global",
      model:"Publicly traded, one of the largest global freight brokers/3PLs; $23B freight under management, 450,000 contract carriers, 83,000 customers, 37M shipments/year.",
      solution:"Freight Claims / Carrier Fraud Agent",
      why:"Named to FreightTech 25 for agentic AI, running 30+ proprietary AI agents in-house — a harder 'buy' for overlapping categories, but its 450,000-carrier network is exposed to fraud/onboarding risk not highlighted in its own announcements.",
      pain:"450,000-carrier network's fraud/claims exposure", buyer:"VP Risk / Claims", strategic:"Under-marketed fraud gap.",
      action:"Outbound — under-marketed fraud/claims gap" },
    { name:"RXO, Inc.", region:"na", hq:"Charlotte, NC", tier:"B", score:"6.60", industry:"Brokerage", geo:"United States",
      model:"Publicly traded, asset-light brokerage spun off from XPO in 2022; Q4 2025 revenue $1.5B (down from $1.7B); brokerage volume down 4% YoY.",
      solution:"Dynamic Procurement / Freight Quoting Agent",
      why:"States its technology 'continues to advance through transformational AI' and is piloting agentic AI/digital bidding — actively investing while facing volume softness, a good combination for a margin-defense pitch.",
      pain:"Volume softness while investing in agentic AI", buyer:"VP Procurement / COO", strategic:"Margin-defense pitch.",
      action:"Outbound — margin-defense angle" },
    { name:"Total Quality Logistics (TQL)", region:"na", hq:"Cincinnati, OH", tier:"C", score:"5.95", industry:"Brokerage", geo:"United States",
      model:"Privately held, one of the largest freight brokerages in North America; 9,000 employees (450 in IT), 40,000 customers, 140,000-carrier network.",
      solution:"Carrier Fraud & Onboarding Agent",
      why:"A 140,000-carrier network is a textbook Carrier Fraud fit, but TQL's CIO publicly favors building in-house over buying — best approached as an API/embedded-technology partner, a longer cycle.",
      pain:"140,000-carrier network; CIO favors build-in-house", buyer:"CIO", strategic:"API/embedded-partner motion.",
      action:"Outbound — API/embedded-partner motion (longer cycle)" },
    { name:"Landstar System", region:"na", hq:"Jacksonville, FL", tier:"B", score:"6.85", industry:"Brokerage / Asset-light", geo:"United States",
      model:"Publicly traded, asset-light model built on independent Business Capacity Owners (BCOs) plus a network of approved third-party carriers; FY2024 revenue $4.8B; 8,843 BCO trucks; 70,000+ approved carriers.",
      solution:"Carrier Fraud & Onboarding Agent",
      why:"70,000+ approved third-party carriers plus thousands of independent BCOs is close to the ideal use case — verification and monitoring at this scale is a massive manual burden today.",
      pain:"70,000+ approved carriers plus BCOs to verify/monitor", buyer:"VP Risk / VP Capacity", strategic:"Ideal-scale fraud/onboarding case.",
      action:"Outbound — verification-at-scale angle" },
    { name:"Covenant Logistics Group", region:"na", hq:"Chattanooga, TN", tier:"C", score:"6.05", industry:"FTL / Brokerage", geo:"United States",
      model:"Publicly traded mid-market truckload carrier (Expedited + Dedicated) plus a Managed Freight brokerage and Warehousing; ≈2,400 average tractors (Q3 2025).",
      solution:"Dynamic Procurement / Freight Quoting Agent",
      why:"Already adopted Parade.ai's capacity-management platform to move its brokerage to digital bookings — real budget and openness to outside AI tools at a scale that resembles Bison and Daylight better than the mega-carriers.",
      pain:"Adopted Parade.ai — openness to outside AI at Bison/Daylight-like scale", buyer:"VP Procurement / COO", strategic:"Scale resembles the warm clients.",
      action:"Outbound — mid-market fit angle" },

    { name:"DSV (post-DB Schenker)", region:"eu", hq:"Hedehusene, Denmark", tier:"A", score:"8.05", industry:"Freight Forwarder / 3PL", geo:"Europe",
      model:"Global freight forwarder (air/sea/road) and contract logistics; completed a ≈€14.3B acquisition of DB Schenker (April 2025), becoming the world's largest freight forwarder; combined revenue ≈€41.6B, ≈160,000 employees, 90+ countries.",
      solution:"Bridge (TMS Integration Gateway)",
      why:"Two full IT/operations stacks are mid-integration right now — probably the single strongest Bridge prospect identified in this entire analysis, and a documented, in-progress technical challenge.",
      pain:"≈€14.3bn merger; two full IT/ops stacks mid-integration", buyer:"Integration program office / CIO", strategic:"Highest-scored prospect overall (8.05).",
      action:"Outbound — target the integration program office" },
    { name:"DHL Global Forwarding, Freight", region:"eu", hq:"Bonn, Germany", tier:"A", score:"7.70", industry:"Freight Forwarder", geo:"Europe",
      model:"DHL Group's air/ocean freight-forwarding and road-freight division; 2025 divisional revenue €18.6B (down 5.1% YoY on rate declines, not volume).",
      solution:"Invoice Audit & Payment Agent",
      why:"Announced 'Accelerated Digitalization' restructuring (Dec 2025) — a new EVP role built around AI-powered customs clearance and back-office digitization — a very recent, C-suite-level, named organizational commitment to exactly this kind of automation.",
      pain:"New EVP role created (Dec 2025) for AI-led digitalization, amid revenue pressure", buyer:"New digitalization EVP org / VP Finance", strategic:"C-suite AI mandate.",
      action:"Outbound — approach the new digitalization organization" },
    { name:"Kuehne+Nagel", region:"eu", hq:"Schindellegi, Switzerland", tier:"B", score:"7.25", industry:"Freight Forwarder", geo:"Europe",
      model:"Global freight forwarder (sea, air, road, contract logistics), asset-light; 2025 net turnover CHF 24.5B, a top-3 global forwarder.",
      solution:"Freight Quoting / Invoice Audit Agent",
      why:"CEO has publicly tied 'accelerated deployment of AI' to a specific productivity timeline (material gains expected from 2027) — one of the clearest executive-level AI commitments found.",
      pain:"CEO-level AI commitment tied to a 2027 productivity timeline", buyer:"VP Digital Transformation", strategic:"Clear executive AI commitment.",
      action:"Outbound — align to the CEO AI timeline" },
    { name:"Wincanton (acquired by GXO)", region:"eu", hq:"Chippenham, UK", tier:"B", score:"7.10", industry:"Contract Logistics", geo:"United Kingdom",
      model:"UK/European contract logistics and warehousing, freshly integrated into GXO's global fulfillment network (27 countries) after a $965M acquisition.",
      solution:"Bridge (TMS Integration Gateway)",
      why:"GXO has explicitly framed the deal around deploying its automation/technology stack across the newly combined UK operation, targeting £45M in annual synergies by year three — a live, funded integration window.",
      pain:"Fresh $965M acquisition; funded integration window", buyer:"CIO / Integration lead", strategic:"Live post-acquisition trigger.",
      action:"Outbound — post-acquisition integration window" },
    { name:"Girteka Logistics", region:"eu", hq:"Vilnius, Lithuania", tier:"B", score:"7.00", industry:"FTL", geo:"Europe",
      model:"Europe's largest private trucking fleet — asset-based FTL road freight, expanding into rail; €1.31B revenue (2025), ≈6,500 tractors, ≈8,000 trailers, ≈15,000 employees.",
      solution:"Dynamic Procurement / Exception Mgmt Agent",
      why:"Running a €120M digital-transformation budget through 2028 with explicit ROI framing (32,000 hours saved in 2025 alone, 40% of orders now digital) — an active, well-funded technology buyer.",
      pain:"€120M digital-transformation budget through 2028", buyer:"VP Digital / COO", strategic:"Well-funded active buyer.",
      action:"Outbound — align to the digital-transformation budget" },
    { name:"Dachser", region:"eu", hq:"Kempten, Germany", tier:"B", score:"6.55", industry:"3PL / Groupage", geo:"Europe",
      model:"Family-owned full-service logistics — European road groupage network plus air/sea freight and contract logistics; record 2025 revenue €8.3B, ≈37,500 employees, 46.7M tons transported.",
      solution:"Invoice Audit / Freight Quoting Agent",
      why:"≈€325M invested in 2025 across network expansion and 'digitalization and climate action,' rising to over €350M planned for 2026 — a large, explicitly-growing digitalization budget.",
      pain:"Rising, explicitly-stated digitalization budget", buyer:"VP Finance / VP Digital", strategic:"Growing digitalization spend.",
      action:"Outbound — reference the digitalization budget" },
    { name:"Raben Group", region:"eu", hq:"Oss, Netherlands (Polish operational base)", tier:"C", score:"6.25", industry:"3PL", geo:"Europe",
      model:"Full-service logistics — international road forwarding, domestic distribution, contract logistics, fresh-food logistics; revenue >€2.3B (2025, +6%), 17 countries, 170+ depots, ≈17.5M shipments/year.",
      solution:"Shipment Exception Mgmt Agent",
      why:"Named 'digital transformation acceleration' as a strategic pillar alongside physical network expansion, and already runs an ETA shipment-tracking solution — real infrastructure to extend.",
      pain:"17-country network; ETA tracking already in place to extend", buyer:"VP Operations", strategic:"Existing ETA layer to extend.",
      action:"Outbound — extend the existing ETA solution" },
    { name:"GEODIS", region:"eu", hq:"Levallois-Perret, France (SNCF Group)", tier:"C", score:"5.90", industry:"3PL", geo:"Europe",
      model:"Full-service logistics across freight forwarding, contract logistics, distribution/express, and road transport; €11.3B revenue (2024), ≈49,720 employees, 166 countries.",
      solution:"Invoice Audit / Exception Mgmt Agent",
      why:"Already runs Locus robotics for e-commerce fulfillment automation — demonstrated willingness to procure and integrate third-party automation technology at scale.",
      pain:"166-country network; fragmented carrier feeds", buyer:"VP Operations / Finance", strategic:"Proven third-party automation buyer.",
      action:"Outbound — third-party automation angle" },
    { name:"GEFCO (contract-logistics division)", region:"eu", hq:"Courbevoie, France (CMA CGM Group)", tier:"C", score:"5.30", industry:"Contract Logistics", geo:"Europe",
      model:"Contract-logistics specialist with an automotive-sector focus plus aerospace/pharma/energy/retail; ≈11,500 employees; ≈$5–6B revenue [ESTIMATE]; 47-country network.",
      solution:"Bridge (TMS Integration Gateway)",
      why:"Recently absorbed into CMA CGM's larger tech ecosystem — worth confirming who now owns logistics-technology purchasing decisions before an outbound approach; see also the Automotive section for its stronger CEVA Vehicle Logistics fit.",
      pain:"Absorbed into CMA CGM tech ecosystem; ownership unclear", buyer:"CMA CGM tech org", strategic:"Confirm decision ownership first.",
      action:"Outbound — confirm decision ownership first" },
    { name:"Waberer's International", region:"eu", hq:"Budapest, Hungary", tier:"D", score:"4.50", industry:"FTL", geo:"Europe",
      model:"Asset-based international road-freight carrier (FTL) and CEE's largest trucking company; Q1 2025 revenue €194.4M (down 1.2%); fleet reduced to 2,719 vehicles as part of restructuring.",
      solution:"Invoice Audit & Payment Agent",
      why:"In active cost-cutting/fleet-shrinking mode rather than technology-investment mode — a weaker near-term fit worth revisiting once restructuring stabilizes rather than approaching today.",
      pain:"Restructuring/cost-cutting mode — weaker near-term fit", buyer:"CFO", strategic:"Revisit after restructuring stabilizes.",
      action:"Nurture — revisit after restructuring" },
    { name:"Culina Group", region:"eu", hq:"Market Drayton, UK (Müller Group)", tier:"D", score:"4.40", industry:"Contract Logistics", geo:"United Kingdom",
      model:"UK food & drink logistics specialist, grown by acquisition into a diversified portfolio (Eddie Stobart, Fowler Welch, Great Bear); ≈£2.2B combined FMCG logistics turnover.",
      solution:"Bridge (TMS Integration Gateway)",
      why:"No public technology signal found — messaging centers on scale via M&A rather than digital transformation — but its acquisition-heavy growth model suggests latent systems fragmentation worth a discovery call rather than ruling out.",
      pain:"Acquisition-heavy growth suggests latent systems fragmentation", buyer:"CIO", strategic:"Discovery call rather than rule out.",
      action:"Nurture — discovery call on systems fragmentation" },

    { name:"Groupe CAT (incl. STVA)", region:"auto", adapted:true, hq:"Levallois-Perret, France", tier:"A", score:"7.65", industry:"Automotive Logistics", geo:"Europe",
      model:"Historical Renault-linked vehicle-logistics group that absorbed rival STVA in 2017 — one of Europe's largest bimodal finished-vehicle fleets; ≈105 compounds, 1,200+ owned trucks with real-time geolocation, €800M vehicle-logistics division revenue (2022), 3.5M vehicles shipped/year.",
      solution:"Empty-Mile / Backhaul Agent (adapted)",
      why:"The largest automotive-logistics scale-peer to Hödlmayr found, and it already has real-time truck geolocation feeding its TMS — the data foundation an AI dispatch/backhaul layer needs already exists.",
      pain:"Largest automotive-logistics scale-peer to Hödlmayr; already has real-time truck geolocation", buyer:"VP Fleet / Transport Ops", strategic:"Automotive-vertical anchor account.",
      action:"Outbound — automotive-vertical playbook" },
    { name:"United Road Services (URS)", region:"auto", adapted:true, hq:"Romulus, MI, USA", tier:"B", score:"7.30", industry:"Automotive Logistics", geo:"United States / Canada",
      model:"North America's largest finished-vehicle carrier/logistics network — road haulage from OEM plants/ports/rail to dealers; 4M+ units/year (US & Canada), 90+ locations, owned by Carlyle Group.",
      solution:"Vehicle Movement Exception Mgmt Agent (adapted)",
      why:"Already runs proprietary optimization/tracking tools — OVISS (order-to-fulfillment tracking), LoadSolver (network optimization), Haully (carrier self-dispatch) — a prime candidate for an AI-agent layer on top of tools it already owns.",
      pain:"Runs OVISS/LoadSolver/Haully — an AI-agent layer opportunity", buyer:"VP Operations", strategic:"Layer on existing tools.",
      action:"Outbound — AI-agent-layer angle" },
    { name:"CEVA Vehicle Logistics (ex-GEFCO)", region:"auto", adapted:true, hq:"France (CMA CGM Group)", tier:"B", score:"6.90", industry:"Automotive Logistics", geo:"Europe",
      model:"Full finished-vehicle logistics — rail/road haulage plus 30 vehicle compounds across Europe, absorbed into CEVA after CMA CGM's 2022 acquisition of GEFCO; 3,000+ rail wagons; Europe ≈50% of CEVA revenue.",
      solution:"Vehicle Movement Exception Mgmt Agent (adapted)",
      why:"30-compound, rail-heavy network is structurally very close to Hödlmayr's own; stated intent to build 'digital tools for vehicle deliveries' for the direct-to-consumer shift.",
      pain:"Rail-heavy 30-compound network; stated D2C digital-tools intent", buyer:"VP Transport / Rail Ops", strategic:"Structural Hödlmayr twin.",
      action:"Outbound — vehicle-movement exception angle" },
    { name:"ARS Altmann AG", region:"auto", adapted:true, hq:"Kolbermoor, Germany", tier:"B", score:"6.90", industry:"Automotive Logistics", geo:"Europe",
      model:"Integrated multimodal vehicle-logistics provider — rail, road, and terminal/compound operations, including port terminals; 3.5M vehicles/year, 4,000+ rail wagons, 850 special trucks, 200 trains/week, 9 hubs.",
      solution:"Vehicle Movement Exception Mgmt Agent (adapted)",
      why:"The closest structural twin to Hödlmayr found in this research — near-identical rail+road+compound model, 200 weekly trains creating real cross-mode handoff complexity.",
      pain:"200 weekly trains; near-identical model to Hödlmayr", buyer:"VP Rail Ops", strategic:"Closest structural twin.",
      action:"Outbound — cross-mode handoff angle" },
    { name:"BLG Logistics (Automobile division)", region:"auto", adapted:true, hq:"Bremen, Germany", tier:"B", score:"6.75", industry:"Automotive Logistics", geo:"Europe",
      model:"Vehicle-logistics operator handling road/rail/river transport, storage, and technical reconditioning (PDI, repairs); ≈4.4–5M vehicles/year, storage for up to 500,000 units across 13 German locations, 15 terminals.",
      solution:"Vehicle Damage & Claims Mgmt Agent (adapted)",
      why:"Very high storage/throughput volume with genuine multimodal complexity (road/rail/river); strong candidate for damage-inspection automation at this scale.",
      pain:"4.4–5M vehicles/year across road/rail/river", buyer:"VP Quality / Operations", strategic:"Damage-inspection automation at scale.",
      action:"Outbound — damage/claims automation angle" },
    { name:"Ryder System (Automotive)", region:"auto", adapted:true, hq:"Miami, FL, USA", tier:"C", score:"6.30", industry:"Automotive 3PL", geo:"United States / Canada / Mexico",
      model:"3PL offering dedicated transportation, warehousing, and JIT delivery for automotive OEMs/Tier 1s; 425+ rental locations, access to 85,000 qualified carriers, confirmed GM relationship (2018/2022 Supplier of the Year).",
      solution:"Vehicle Movement Exception Mgmt Agent (adapted)",
      why:"Already runs RyderShare (visibility/analytics) and RyderShip — a strong existing foundation to extend with an AI agent for ETA prediction and dispatch/carrier management.",
      pain:"RyderShare/RyderShip foundation to extend", buyer:"VP Automotive / Operations", strategic:"Brokerage-side fit; large NA footprint.",
      action:"Outbound — extend RyderShare with an agent layer" },
    { name:"Wallenius Wilhelmsen", region:"auto", adapted:true, hq:"Oslo, Norway", tier:"C", score:"5.65", industry:"Automotive Logistics (RoRo)", geo:"Global",
      model:"Ocean RoRo carrier plus an inland/processing-center network — PDI, accessory installation, mechanical/paint repair, storage, yard management at ports and plants; global network, auto-OEM contracts.",
      solution:"Vehicle Damage & Claims Mgmt Agent (adapted)",
      why:"Ocean-to-inland handoff complexity plus PDI/EV workflows fit exception-management and damage/claims use cases well; already runs a Track & Trace service and MyPortal customer portal.",
      pain:"Ocean-to-inland PDI/damage workflow", buyer:"VP Quality / Operations", strategic:"PDI/EV damage workflows.",
      action:"Outbound — PDI/damage-claims angle" },
    { name:"Mosolf Group", region:"auto", adapted:true, hq:"Kirchheim unter Teck, Germany", tier:"C", score:"5.40", industry:"Automotive Logistics", geo:"Europe",
      model:"Full-chain automotive logistics — line-off/release services, intermodal transport, port logistics, and technical services (workshops, paint) via specialized subsidiaries.",
      solution:"Vehicle Damage & Claims Mgmt Agent (adapted)",
      why:"Technical-services and retail-delivery chain (PDI-adjacent) is a strong structural match for damage/claims management, though public technology and scale data is limited.",
      pain:"PDI-adjacent technical-services chain", buyer:"VP Quality", strategic:"Structural claims match.",
      action:"Outbound — damage/claims angle (limited public data)" },
    { name:"CFR Rinkens (DP World)", region:"auto", adapted:true, hq:"Long Beach, CA, USA (DP World)", tier:"C", score:"5.40", industry:"Automotive Logistics", geo:"United States",
      model:"Specialist in containerized finished-vehicle and semi-knock-down shipping, plus racking systems, expanding into EV/battery logistics; acquired by DP World in October 2023.",
      solution:"Vehicle Movement Exception Mgmt Agent (adapted)",
      why:"Container/port-based model is well suited to shipment exception management and ETA prediction across ocean-to-inland handoffs; fresh post-acquisition integration into DP World is a live trigger.",
      pain:"Ocean-to-inland container handoffs; DP World integration", buyer:"VP Operations", strategic:"Post-acquisition trigger.",
      action:"Outbound — ETA/exception angle" },
    { name:"Neovia Logistics", region:"auto", adapted:true, hq:"Irving, TX, USA", tier:"C", score:"5.30", industry:"Automotive 3PL", geo:"Global",
      model:"3PL spun from Caterpillar/Cummins logistics; automotive is a core vertical spanning production-line to service-parts delivery (aftermarket-weighted, not pure finished-vehicle); confirmed Jaguar Land Rover contract.",
      solution:"Vehicle Damage & Claims Mgmt Agent (adapted)",
      why:"Runs a proprietary 'Neovia Operating System' (lean six-sigma data-capture framework) — a natural integration point for AI-driven claims/exception management and quality-data automation.",
      pain:"NOS data-capture framework to build on", buyer:"VP Quality / Operations", strategic:"Quality-data automation.",
      action:"Outbound — build on the NOS framework" }
  ],

  scoringCriteria: [
    ["Solution Fit","25%"], ["Business Pain / Urgency","15%"], ["Company Scale / Revenue Potential","15%"],
    ["AI-Agent Suitability","10%"], ["ROI Potential","10%"], ["Technology / Data Readiness","10%"],
    ["Similarity to Existing Client Success","10%"], ["Strategic Value / Reference Potential","5%"]
  ],

  /* Solution -> ranked prospects (mix of clients + prospects). Names match clients[].name / prospects[].name. */
  solutionProspects: {
    "invoice-audit": [
      ["Daylight Transport","≈2,500 invoices/day already flowing through an EDI-integrated TMS"],
      ["Bison Transport","Already selected Navix for freight-audit automation — proven budget"],
      ["DHL Global Forwarding, Freight","New EVP role built around AI-led digitalization"],
      ["Forward Air (incl. Omni Logistics)","Active post-merger invoice/systems disruption"],
      ["Werner Enterprises","Publicly guided $45M cost-savings target"],
      ["Knight-Swift Transportation","Multi-segment invoice complexity incl. folded-in U.S. Xpress"],
      ["TForce Freight (TFI International)","19 operating companies, fragmented legacy billing"],
      ["Estes Express Lines","300+ terminal LTL invoice volume and multi-terminal billing complexity"],
      ["Old Dominion Freight Line","High-density interline/accessorial billing volume"],
      ["Dachser","Rising, explicitly-stated digitalization budget"]
    ],
    "exception-mgmt": [
      ["J.B. Hunt Transport Services","New Google Cloud alliance for supply-chain technology"],
      ["Bison Transport","Existing 'Advanced Warning' disruption-detection product"],
      ["Daylight Transport","Time-critical model makes exceptions proportionally costly"],
      ["Saia, Inc.","Greenfield terminals running poor operating ratios"],
      ["Raben Group","Existing ETA shipment-tracking solution to extend"],
      ["Girteka Logistics","€120M digital-transformation budget through 2028"],
      ["Groupe CAT (incl. STVA)","Real-time truck geolocation across 105 compounds (adapted)"],
      ["Ryder System (Automotive)","Existing RyderShare visibility layer to extend (adapted)"],
      ["CFR Rinkens (DP World)","Ocean-to-inland handoff exception surface (adapted)"],
      ["Estes Express Lines","Active 2025 network expansion strains exception handling"]
    ],
    "claims": [
      ["Hödlmayr International","Existing 360° vehicle-photography claims-evidence workflow (adapted)"],
      ["BLG Logistics (Automobile division)","4.4–5M vehicles/year storage/throughput volume (adapted)"],
      ["Wallenius Wilhelmsen","Ocean-to-inland PDI/damage workflow (adapted)"],
      ["Daylight Transport","MyDaylight claims-intake portal already exists"],
      ["Bison Transport","Meaningful claims volume despite a strong safety record"],
      ["Mosolf Group","Technical-services/PDI chain is claims-adjacent (adapted)"],
      ["Neovia Logistics","Proprietary data-capture framework (NOS) to build on (adapted)"],
      ["C.H. Robinson","450,000-carrier network's claims exposure, an under-marketed gap"],
      ["Estes Express Lines","Claims volume implied by 300+ terminal LTL scale"],
      ["TForce Freight (TFI International)","19 operating companies' claims processes likely fragmented"]
    ],
    "carrier-fraud": [
      ["Bison Transport","Tens-of-thousands-truck brokerage carrier network"],
      ["Total Quality Logistics (TQL)","140,000-carrier network — textbook fraud-agent scale"],
      ["Landstar System","70,000+ approved third-party carriers plus BCOs"],
      ["C.H. Robinson","450,000 contract carriers"],
      ["TForce Freight (TFI International)","Large cross-border US/Canada carrier network"],
      ["Knight-Swift Transportation","Large owner-operator and acquired-fleet network"],
      ["DSV (post-DB Schenker)","Combined carrier network from two merged forwarders"],
      ["GEFCO (contract-logistics division)","47-country carrier/subcontractor network"],
      ["RXO, Inc.","Brokerage carrier network exposed to fraud risk"],
      ["Estes Express Lines","Interline carrier network at 300+ terminal scale"]
    ],
    "freightlink": [
      ["Covenant Logistics Group","Mid-market scale matches FreightLink's 50–2,000 load/mo sweet spot"],
      ["RXO, Inc.","Digital freight platform already customer-facing"],
      ["Raben Group","17-country network needs unified visibility"],
      ["Girteka Logistics","Large FTL fleet, active digital-transformation budget"],
      ["GEODIS","166-country network, fragmented carrier feeds"],
      ["Waberer's International","CEE network could use consolidated tracking"],
      ["Old Dominion Freight Line","$50M capex line includes visibility technology"],
      ["Estes Express Lines","300+ terminal interline network"],
      ["Total Quality Logistics (TQL)","140,000-carrier network needs unified tracking"],
      ["Wincanton (acquired by GXO)","Post-acquisition network consolidation"]
    ],
    "bridge": [
      ["DSV (post-DB Schenker)","Two full IT stacks mid-integration — the strongest Bridge case found"],
      ["TForce Freight (TFI International)","19 separate LTL operating companies on fragmented TMS"],
      ["Wincanton (acquired by GXO)","Fresh $965M acquisition, funded integration window"],
      ["Culina Group","Acquisition-heavy growth (Eddie Stobart, Fowler Welch, Great Bear)"],
      ["GEFCO (contract-logistics division)","Recently absorbed into CMA CGM's tech ecosystem"],
      ["Bison Transport","2025 MasterMind TMS consolidation still maturing"],
      ["Hödlmayr International","Gartner KG acquisition closing summer 2026 (adapted)"],
      ["Forward Air (incl. Omni Logistics)","Two merged companies' systems colliding"],
      ["Landstar System","Network of 70,000+ carriers on varied systems"],
      ["Waberer's International","CEE-region legacy systems, restructuring underway"]
    ]
  },

  /* Buyer personas mapped to the 7 prioritized solutions */
  personas: [
    { key:"invoice-audit", solution:"Invoice Audit & Payment Agent", buyer:"VP Transportation / Director of Freight Payment", econ:"CFO / VP Finance",
      pain:"Manual audit catches only a fraction of billing errors", value:"Self-funding — paid from recovered savings", kpi:"% of spend recovered; days to resolved payment" },
    { key:"exception-mgmt", solution:"Shipment Exception Mgmt Agent", buyer:"VP Operations / control-tower lead", econ:"COO",
      pain:"Exceptions caught late cascade into detention, expedite cost, churn", value:"OTIF protection and cost avoidance", kpi:"OTIF %; exception resolution time" },
    { key:"claims", solution:"Freight Claims Mgmt Agent", buyer:"Claims Manager / Director of Claims", econ:"VP Finance / CFO",
      pain:"Fewer than half of eligible claims are ever filed", value:"Recovery-rate improvement, largely self-funding", kpi:"Claims filed as % eligible; recovery rate" },
    { key:"carrier-fraud", solution:"Carrier Fraud & Onboarding Agent", buyer:"Head of Carrier Procurement / VP Brokerage", econ:"COO / VP Risk",
      pain:"Fraud losses rising; verification-only tools don't monitor continuously", value:"Loss avoidance / insurance-risk reduction", kpi:"Onboarding cycle time; fraud incidents avoided" },
    { key:"procurement", solution:"Dynamic Freight Procurement Agent", buyer:"VP Procurement / VP Transportation", econ:"CFO / VP Supply Chain",
      pain:"High tender-rejection rates, expensive spot-market fallback", value:"Freight-cost reduction vs. market benchmark", kpi:"Cost per mile vs. market; tender acceptance rate" },
    { key:"detention", solution:"Detention & Dock Coordination Agent", buyer:"Head of Dispatch / VP Operations", econ:"COO",
      pain:"Detention billed but rarely collected; driver-retention drag", value:"Recovered detention revenue, driver retention", kpi:"Detention hours/stop; invoice collection rate" },
    { key:"freightlink", solution:"FreightLink (Visibility Hub)", buyer:"VP Operations / Customer Service leadership", econ:"COO",
      pain:"Customer service spends hours/day manually calling carriers for status", value:"CS efficiency and customer retention", kpi:"% of shipments with real-time visibility" }
  ],
  personasNote:"Other titles in the buying committee — CIO/CTO (Bridge, systems-consolidation deals), VP Digital Transformation (DHL's new EVP role, Kuehne+Nagel's CEO-level AI commitment), and Head of Supply Chain (Dynamic Procurement, FreightLink) — are folded into the Buyer/Economic Buyer columns where the researched evidence names them directly.",

  /* Sales messaging (outcome-first) for the Top 5 */
  messaging: [
    { key:"invoice-audit", solution:"Invoice Audit, Discrepancy Resolution & Payment Agent",
      problem:"Freight invoices carry billing errors at a rate finance teams already suspect but rarely quantify — and today's audit process catches only a fraction of it.",
      outcome:"2–8% of audited freight spend recovered annually, funded entirely from the savings it finds.",
      whyAgent:"It doesn't stop at flagging a discrepancy — it drafts the dispute, negotiates within a set threshold, and releases payment, closing a loop a dashboard or rules engine leaves open.",
      whyNow:"Freight-spend growth is outpacing finance headcount at most carriers and shippers, and a self-funding model removes the usual budget fight.",
      opener:"“How much of your freight spend gets a full line-by-line audit today, and what happens to the rest?”",
      pilot:"A 60–90 day pilot on one division's historical invoices, benchmarked against the current process, paid only from what it recovers." },
    { key:"exception-mgmt", solution:"Shipment Exception Management & Disruption Response Agent",
      problem:"Exceptions multiply faster than headcount at scale — a control tower built for hundreds of alerts a week breaks down at thousands.",
      outcome:"Faster resolution, protected OTIF, and avoided expedite cost.",
      whyAgent:"It moves from alerting a human to reasoning about materiality and acting — contacting carriers, rebooking, notifying customers — without waiting for someone to read the alert.",
      whyNow:"Competitors like project44 are already shipping agentic exception handling — the 'just alert, let a human decide' era is ending.",
      opener:"“When a shipment goes off-plan today, how long does it sit before a person notices and acts?”",
      pilot:"A single-mode/region pilot layered on an existing tracking feed, measured against current resolution time." },
    { key:"claims", solution:"Freight Claims Management & Recovery Agent",
      problem:"Most eligible freight claims are never filed — not because they're not worth it, but because filing is manual and easy to deprioritize.",
      outcome:"Recovery rate roughly doubles versus a manual baseline.",
      whyAgent:"It proactively detects claim-eligible exceptions from POD/BOL data instead of waiting to be told, and files, chases, and appeals on its own.",
      whyNow:"This is rated White Space — the least crowded opportunity evaluated anywhere in this analysis — early movers get it before it's competitive.",
      opener:"“Of the claims you're actually eligible to file, what share do you think you're catching today?”",
      pilot:"An 8–12 week LTL-focused pilot, with filing rate and recovery rate measured against the existing baseline." },
    { key:"carrier-fraud", solution:"Carrier Identity, Onboarding & Fraud-Prevention Agent",
      problem:"Cargo-theft and identity-fraud losses are up sharply while most verification tools only check a carrier once, at onboarding.",
      outcome:"Continuous monitoring catches fraud signals a point-in-time check misses.",
      whyAgent:"It doesn't just verify once — it continuously risk-scores, and can pause a load in real time on an active fraud signal.",
      whyNow:"Fraud losses are rising faster than most carrier networks are growing — the exposure compounds every month this goes unaddressed.",
      opener:"“If a carrier's insurance lapsed or their authority changed today, how would you find out?”",
      pilot:"An onboarding-verification MVP against 1–2 vetting APIs for a defined slice of new carriers." },
    { key:"freightlink", solution:"FreightLink — Unified Visibility Hub",
      problem:"Customer service still spends hours a day manually calling carriers for shipment status.",
      outcome:"Real-time visibility without the manual chase.",
      whyAgent:"Positioned honestly: FreightLink is AI-assisted automation, not a full autonomous agent — it's the data foundation that makes agents like Shipment Exception Management possible, with predictive ETA modeling doing the heavy lifting.",
      whyNow:"The fastest, lowest-effort MVP of anything in the portfolio — pre-built connectors already cover most of the North American carrier base.",
      opener:"“How many hours a day does your team spend just calling carriers to ask where a shipment is?”",
      pilot:"A live tracking feed stood up against a defined carrier/lane set — typically the fastest pilot ideyaLabs can offer." }
  ],

  /* Highest-priority sales opportunities (sortable). priorityRank used for sorting. */
  opportunities: [
    { client:"Bison Transport", type:"Existing client", solution:"Invoice Audit & Payment Agent", geo:"Canada/US", customerType:"Carrier + Brokerage", fit:"A", priority:"Approach first",
      whyNow:"Active OIA relationship to extend; Navix selection proves budget/appetite.", problem:"Multi-division invoice audit already outsourced to Navix (2026).",
      buyer:"VP Finance (econ: CFO)", value:"Self-funding; differentiation vs. audit-only Navix.", pilot:"One division's invoices, 60–90 days, benchmarked vs. Navix.", kpi:"% of audited spend recovered; days to resolved payment." },
    { client:"Daylight Transport", type:"Existing client", solution:"Invoice Audit & Payment Agent", geo:"United States", customerType:"Expedited LTL", fit:"A", priority:"Approach first",
      whyNow:"Cleanest, most precisely quantified opportunity; no incumbent conflict.", problem:"≈2,500 invoices/day through an EDI-210-integrated TMS.",
      buyer:"CIO or VP Finance", value:"Self-funding; connects via Daylight's own Boomi pattern.", pilot:"60–90 day pilot via Boomi against the EDI 210 feed.", kpi:"% of audited spend recovered; reduced reconciliation load." },
    { client:"Hödlmayr International", type:"Existing client", solution:"Vehicle Damage & Claims Mgmt Agent (adapted)", geo:"Europe", customerType:"Automotive Logistics", fit:"B", priority:"Validate first",
      whyNow:"Strongest-evidenced Hödlmayr opportunity; 360° photography already exists.", problem:"Vehicle-condition documentation exists; claims filing not shown to be automated.",
      buyer:"VLC Operations / Quality leadership", value:"Differentiated, novel agentic use case; best AI showcase.", pilot:"Scoping conversation first; then single-VLC, single-damage-category.", kpi:"Claims filed as % of damage detected; claim cycle time." },
    { client:"Estes Express Lines", type:"Tier A prospect", solution:"Invoice Audit / Exception Mgmt / Bridge", geo:"United States", customerType:"LTL", fit:"A", priority:"Outbound now",
      whyNow:"300+ terminal LTL network with ≈7% of footprint under construction (2025) — high invoice volume and complexity.", problem:"300+ terminal LTL network; ≈7% of footprint under construction (2025).",
      buyer:"VP Finance / VP Operations", value:"Invoice-audit / exception-management fit backed by network scale.", pilot:"Discovery + tailored pilot.", kpi:"Depends on solution selected." },
    { client:"Schneider National", type:"Tier A prospect", solution:"Detention & Dock Coordination Agent", geo:"United States", customerType:"FTL", fit:"A", priority:"Outbound now",
      whyNow:"EXL AI partnership cut appointment cycle time 50% — proven appetite.", problem:"Appointment-scheduling automation is a funded, proven priority.",
      buyer:"VP Operations / COO", value:"Reference the EXL result directly.", pilot:"Detention/appointment pilot on a high-volume facility set.", kpi:"Detention hours/stop; appointment cycle time." },
    { client:"DSV (post-DB Schenker)", type:"Tier A prospect", solution:"Bridge (TMS Integration Gateway)", geo:"Europe", customerType:"Freight Forwarder / 3PL", fit:"A", priority:"Outbound now",
      whyNow:"≈€14.3bn merger; two IT/ops stacks mid-integration — strongest Bridge case.", problem:"Two full stacks mid-integration right now.",
      buyer:"Integration program office / CIO", value:"Documented, in-progress technical challenge.", pilot:"Scoped integration pilot on one trading-partner set.", kpi:"Trading-partner onboarding time." },
    { client:"TForce Freight (TFI International)", type:"Tier A prospect", solution:"Bridge (TMS Integration Gateway)", geo:"US/Canada", customerType:"LTL", fit:"A", priority:"Outbound now",
      whyNow:"19 operating companies on fragmented legacy TMS — textbook Bridge.", problem:"19 separate LTL operating companies, likely fragmented legacy TMS.",
      buyer:"CIO / VP IT", value:"Systems-consolidation angle.", pilot:"Bridge pilot on one operating company's integration.", kpi:"Trading-partner onboarding time." },
    { client:"J.B. Hunt Transport Services", type:"Tier A prospect", solution:"Shipment Exception Mgmt Agent", geo:"United States", customerType:"FTL / Brokerage", fit:"A", priority:"Outbound now",
      whyNow:"ICS volume -7% YoY + new Google Cloud AI alliance.", problem:"Declining brokerage volume; actively seeking a technology edge.",
      buyer:"VP Operations / control-tower lead", value:"Align with the Google Cloud initiative.", pilot:"Single-mode/region exception pilot.", kpi:"OTIF %; exception resolution time." },
    { client:"DHL Global Forwarding, Freight", type:"Tier A prospect", solution:"Invoice Audit & Payment Agent", geo:"Europe", customerType:"Freight Forwarder", fit:"A", priority:"Outbound now",
      whyNow:"New EVP role (Dec 2025) for AI-led digitalization amid revenue pressure.", problem:"Revenue pressure; C-suite mandate for back-office digitization.",
      buyer:"New digitalization EVP org / VP Finance", value:"Self-funding automation matching the stated mandate.", pilot:"Invoice-audit pilot on one region's invoices.", kpi:"% of audited spend recovered." },
    { client:"Groupe CAT / STVA", type:"Tier A prospect", solution:"Empty-Mile / Backhaul (adapted)", geo:"Europe", customerType:"Automotive Logistics", fit:"A", priority:"Outbound now",
      whyNow:"Largest automotive scale-peer to Hödlmayr; already has real-time truck geolocation.", problem:"Return-leg utilization gaps on specialized car-carrier equipment.",
      buyer:"VP Fleet / Transport Ops", value:"Data foundation for a backhaul layer already exists.", pilot:"One regional fleet — measure empty-leg % first.", kpi:"Empty-leg percentage." }
  ],

  actionPlan: [
    { window:"Days 1–30", account:"Bison Transport", solution:"Invoice Audit & Payment Agent",
      action:"Re-engage on the Order Intelligence Agent relationship; introduce Invoice Audit as a natural next step (shared document-intelligence infrastructure), positioned alongside — not against — the existing Navix relationship.",
      outcome:"Second engagement opened at a warm account.", kpi:"Meeting booked with the OIA relationship owner + VP Finance." },
    { window:"Days 1–30", account:"Daylight Transport", solution:"Invoice Audit & Payment Agent",
      action:"Open outreach to the CIO/VP Finance with a pilot proposal built around its own EDI 210/Boomi integration pattern — the most quantified, lowest-friction opportunity in this document.",
      outcome:"Pilot conversation opened at the cleanest-data account.", kpi:"Pilot scope agreed; sample invoice access requested." },
    { window:"Days 1–30", account:"Seven Tier A prospects", solution:"Trigger-specific",
      action:"Begin outbound sequencing to Schneider National, Estes Express Lines, TForce Freight, J.B. Hunt, DSV, DHL Global Forwarding–Freight, and Groupe CAT/STVA — each opening with its own sourced trigger rather than a generic pitch.",
      outcome:"Tier A pipeline initiated.", kpi:"First-meeting rate across the seven." },
    { window:"Days 1–30", account:"Estes Express Lines", solution:"Invoice Audit / Exception Mgmt / Bridge",
      action:"Open outbound to VP Finance / VP Operations, leading with the invoice-audit / exception-management fit for a 300+ terminal LTL network.",
      outcome:"Cold account opened on the invoice-audit / exception-management fit.", kpi:"Reply/meeting from the outreach." },
    { window:"Days 31–60", account:"Hödlmayr International", solution:"Vehicle Damage & Claims Mgmt Agent (adapted)",
      action:"Hold a scoping/validation conversation with VLC Operations or Quality leadership around the adapted agent, using the 360° photography workflow as the opener — do not propose a pilot before this confirms the gap.",
      outcome:"Process-gap confirmed (or disconfirmed) before any build.", kpi:"Validation conversation completed." },
    { window:"Days 31–60", account:"Schneider National & TForce Freight", solution:"Public-data outreach",
      action:"Prepare tailored public-data outreach for these next-highest Tier A NA prospects (disclosed capex and M&A-integration facts respectively).",
      outcome:"Two more cold accounts openable without a warm intro.", kpi:"Two outreach pieces delivered + sent." },
    { window:"Days 31–60", account:"Bison & Daylight", solution:"Invoice Audit & Payment Agent",
      action:"Move both from first conversation to a scoped 6–12 week pilot proposal, using the pilot definitions in the client deep dives.",
      outcome:"Two scoped pilot proposals on the table.", kpi:"Signed pilot scope at ≥1 of the two." },
    { window:"Days 31–60", account:"Tier B prospects", solution:"Trigger-specific",
      action:"Begin outbound to Tier B in parallel, prioritizing the most recent dated triggers — Wincanton/GXO's post-acquisition integration window and ArcBest's proven internal AI ROI are the strongest.",
      outcome:"Tier B pipeline initiated.", kpi:"First-meeting rate across priority Tier B." },
    { window:"Days 61–90", account:"Bison and/or Daylight", solution:"Invoice Audit & Payment Agent",
      action:"Launch the pilot(s), instrumented against the defined KPIs from day one so the results are case-study-ready at pilot end.",
      outcome:"Live pilot generating measurable data.", kpi:"Pilot live; KPI instrumentation in place." },
    { window:"Days 61–90", account:"Tier A conversations", solution:"Sales-messaging pack",
      action:"Convert Tier A outbound conversations that have progressed into scoped pilot proposals, using the sales-messaging pack.",
      outcome:"Tier A pilots scoped.", kpi:"Scoped proposals from progressed Tier A conversations." },
    { window:"Days 61–90", account:"Bison/Daylight pilot data", solution:"ROI hypothesis review",
      action:"Review pilot data against the ROI hypotheses in this document, and correct any hypothesis the real data disproves.",
      outcome:"Validated (or corrected) ROI hypotheses.", kpi:"Pilot data reviewed vs. hypotheses." }
  ],

  finalRecommendations: [
    ["Which existing client to approach FIRST?","Bison and Daylight in parallel, for different reasons. Bison because an active, scoped relationship (OIA) already exists — the fastest path to a second signed engagement. Daylight because it is the cleanest, most precisely quantified opportunity with no incumbent-vendor narrative. Hödlmayr follows both, after a validation conversation rather than a pilot pitch."],
    ["Which solution to propose?","Invoice Audit & Payment Agent to both Bison and Daylight (both HIGH FIT, concrete pilot definitions exist, shared document-intelligence pattern). For Hödlmayr, the Vehicle Damage & Claims Management Agent (adapted) as the opening conversation, not a formal pilot."],
    ["What should the pilot look like?","Bison: one division's invoices, 60–90 days, benchmarked vs. the Navix/manual baseline. Daylight: 60–90 day pilot via Boomi against the EDI 210 feed. Hödlmayr: no pilot yet — a scoping conversation first, then single-site/single-damage-category only once the gap is confirmed."],
    ["Which client becomes the flagship case study?","Daylight Transport — quantifiable before/after invoice-audit numbers, a single clean integration story (Boomi/TruckMate), and no multi-vendor narrative to explain."],
    ["Which 10 new prospects to target immediately?","The seven Tier A (Estes, Schneider, TForce, J.B. Hunt, DSV, DHL Global Forwarding–Freight, Groupe CAT/STVA), plus ArcBest, Wincanton/GXO, and Ryder System to round out ten. Each opens with its own sourced trigger."],
    ["Which 3 agents have the broadest addressable base?","Freight Visibility & ETA (FreightLink) — the widest ICP; Invoice Audit & Payment (every carrier/broker with third-party freight spend); and Detention & Dock Scheduling (everywhere a physical dock/yard exists)."],
    ["Which agent generates revenue quickest?","Invoice Audit & Payment Agent — shortest, most concrete pilot definitions already scoped at two clients, the most directly measurable ROI, and the lowest data-integration lift of the top-tier solutions."],
    ["Which agent has the strongest strategic differentiation?","The Vehicle Damage & Claims Management Agent (Hödlmayr-adapted) — no freight-focused AI competitor is positioned to build it; it requires computer-vision-grade image analysis on an automotive-logistics claims workflow."],
    ["Which vertical to prioritize?","LTL then FTL asset-based carriers — where both warm relationships sit, where the deepest Tier A/B bench exists, and where the core solution set needs the least adaptation. Automotive logistics (via Hödlmayr) as a strategic, differentiation-led second vertical."],
    ["Horizontal platform or verticalized agents?","A horizontal platform with a small number of vertical adaptations. Most of the Top 7 apply across LTL/FTL/brokerage with little change; automotive is the one case justifying dedicated adaptation, built as a configuration layer on the shared platform so engineering compounds rather than fragmenting."],
    ["What should sales do in the next 90 days?","Re-engage Bison and open Daylight in the first 30 days; begin outbound to the seven core Tier A prospects with client-specific triggers; hold the Hödlmayr validation conversation and scope pilot proposals in days 31–60; launch the Bison/Daylight pilot(s) — instrumented from day one — in days 61–90."]
  ],

  disclaimer:"This is a strategy and prioritization framework, not a guarantee of client need or deal outcome. Every client-specific problem statement is flagged as FACT, ASSESSMENT/INFERENCE, or NEEDS CLIENT VALIDATION; every new-prospect fit is built on sourced, publicly available information, not invented company data. The next step for every recommendation is a validation conversation, not a signed pilot."
};
